import {
  CircleUser,
  Settings,
  Heart,
  Star,
  Bell,
  LogOut,
  Menu,
  Bookmark,
  PlusCircle,
  Home,
  LayersPlus,
  UserStar,
  Puzzle,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

export const Icons = {
  user: CircleUser,
  settings: Settings,
  heart: Heart,
  star: Star,
  bell: Bell,
  logout: LogOut,
  menu: Menu,
  bookmark: Bookmark,
  plus: PlusCircle,
  home: Home,
  listing: LayersPlus,
  userStar: UserStar,
  puzzle: Puzzle,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
} as const;
