import {
  CircleUser,
  Settings,
  Heart,
  Star,
  Bell,
  LogOut,
  Menu,
  Bookmark,
  PlusCircle,
  Home,
  LayersPlus,
  UserStar,
  Puzzle,
  ChevronDown,
  ChevronUp,
  MoveLeft,
  MoveRight,
  Smile,
  NotebookPen,
  Eye,
  Clock,
  MapPin,
  DatabaseX,
} from "lucide-react";

export const Icons = {
  user: CircleUser,
  settings: Settings,
  heart: Heart,
  star: Star,
  bell: Bell,
  logout: LogOut,
  menu: Menu,
  bookmark: Bookmark,
  plus: PlusCircle,
  home: Home,
  listing: LayersPlus,
  userStar: UserStar,
  puzzle: Puzzle,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  moveLeft: MoveLeft,
  moveRight: MoveRight,
  smile: Smile,
  notebookPen: NotebookPen,
  view: Eye,
  time: Clock,
  location: MapPin,
  databaseX: DatabaseX,
} as const;
